In [1]:
import pandas as pd
import numpy as np
import kagglehub
from dotenv import load_dotenv
from pathlib import Path
from kagglehub import KaggleDatasetAdapter

/Users/ak007/ML/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
load_dotenv()

True

In [3]:
cwd = Path.cwd()
project_root = cwd.parent

In [4]:
df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "uciml/breast-cancer-wisconsin-data",
    "data.csv" 
)

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.shape

(569, 33)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [8]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [9]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [10]:
df.drop(columns=["Unnamed: 32"], inplace=True)

In [11]:
dia = df["diagnosis"].value_counts()

In [12]:
dia_per = (dia/ dia.sum())*100
dia_per

diagnosis
B    62.741652
M    37.258348
Name: count, dtype: float64

In [13]:
df["diagnosis"] = df["diagnosis"].replace({"B":1, "M": -1})

/var/folders/69/dxynlnqj6413x3bgy4c63zhc0000gn/T/ipykernel_3299/795858076.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["diagnosis"] = df["diagnosis"].replace({"B":1, "M": -1})


In [14]:
df["diagnosis"].value_counts()

diagnosis
 1    357
-1    212
Name: count, dtype: int64

In [15]:
df_shuffled = df.sample(frac=1)

In [16]:
X_train = df_shuffled[[col for col in df_shuffled.columns if col not in ["id", "diagnosis"]]].iloc[:int(0.8*df_shuffled.shape[0])]
Y_train = df_shuffled["diagnosis"].iloc[:int(0.8*df_shuffled.shape[0])]
X_test = df_shuffled[[col for col in df_shuffled.columns if col not in ["id", "diagnosis"]]].iloc[int(0.8*df_shuffled.shape[0]):]
Y_test = df_shuffled["diagnosis"].iloc[int(0.8*df_shuffled.shape[0]):]
X_train = X_train.to_numpy()
Y_train = Y_train.to_numpy()
X_test = X_test.to_numpy()
Y_test = Y_test.to_numpy()

In [17]:
# Let's standardize the data
X_train = (X_train - X_train.mean(axis=0))/X_train.std(axis=0)
Y_train = Y_train.reshape((X_train.shape[0], 1))
X_test = (X_test - X_test.mean(axis=0))/X_test.std(axis=0)
Y_test = Y_test.reshape((X_test.shape[0], 1))

In [18]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((455, 30), (455, 1), (114, 30), (114, 1))

In [19]:
def calculate_loss(w, b, X, Y, C=1.0):
    hinge_loss = np.maximum(0, 1 - Y * (X @ w + b)).sum()
    loss = 0.5 * (w.T @ w) + C * hinge_loss
    return loss.item()

In [20]:
# testing the calculate_loss function
w = np.zeros(shape=(X_train.shape[1]))
b = np.zeros(shape=(1))
w, b

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0.]))

In [21]:
calculate_loss(w=w, b=b, X=X_train, Y=Y_train)

207025.0

In [22]:
def check(w, b, X, Y):
    return Y * (X @ w + b) >= 1

In [23]:
def calculating_gradients(w, b, X, Y, C):
    result = check(w, b, X, Y).squeeze()
    dl_dw = w - C * (X[~result] * Y[~result]).sum(axis=0, keepdims=True).T / X.shape[0]
    dl_db = -C * Y[~result].sum()
    return dl_dw, dl_db

In [24]:
def update_params(w, b, X, Y, C, lr=3e-2):
    dl_dw, dl_db = calculating_gradients(w, b, X, Y, C)
    new_w = w - lr * dl_dw
    new_b = b - lr * dl_db
    return new_w, new_b

In [25]:
def train_soft_margin_svm(X, Y, C, lr=3e-2, epochs=10):
    w = np.zeros(shape=(X.shape[1], 1))
    b = np.zeros(shape=(1, 1))

    for epoch in range(epochs):
        w, b = update_params(w, b, X, Y, C, lr)
        cost = calculate_loss(w, b, X, Y, C)
        print(f"Epoch: {epoch+1}/{epochs}, Cost: {cost:.2f}")

    return w, b

In [26]:
t_w, t_b = train_soft_margin_svm(
    X=X_train,
    Y=Y_train,
    lr=1e-3,
    epochs=100,
    C=5.0
)

Epoch: 1/100, Cost: 1854.69
Epoch: 2/100, Cost: 1737.86
Epoch: 3/100, Cost: 1878.57
Epoch: 4/100, Cost: 1486.05
Epoch: 5/100, Cost: 1444.74
Epoch: 6/100, Cost: 1407.52
Epoch: 7/100, Cost: 1440.58
Epoch: 8/100, Cost: 1599.90
Epoch: 9/100, Cost: 1277.74
Epoch: 10/100, Cost: 1325.21
Epoch: 11/100, Cost: 1348.78
Epoch: 12/100, Cost: 1340.28
Epoch: 13/100, Cost: 1166.05
Epoch: 14/100, Cost: 1211.88
Epoch: 15/100, Cost: 1122.52
Epoch: 16/100, Cost: 1123.06
Epoch: 17/100, Cost: 1070.60
Epoch: 18/100, Cost: 1029.22
Epoch: 19/100, Cost: 991.85
Epoch: 20/100, Cost: 947.35
Epoch: 21/100, Cost: 913.13
Epoch: 22/100, Cost: 889.56
Epoch: 23/100, Cost: 852.59
Epoch: 24/100, Cost: 829.43
Epoch: 25/100, Cost: 818.36
Epoch: 26/100, Cost: 781.18
Epoch: 27/100, Cost: 772.34
Epoch: 28/100, Cost: 751.01
Epoch: 29/100, Cost: 746.29
Epoch: 30/100, Cost: 712.39
Epoch: 31/100, Cost: 713.29
Epoch: 32/100, Cost: 682.01
Epoch: 33/100, Cost: 681.35
Epoch: 34/100, Cost: 663.90
Epoch: 35/100, Cost: 658.05
Epoch: 36/1

In [27]:
def predictions(trained_w, trained_b, X):
    raw_preds = X @ trained_w + trained_b
    raw_preds = np.where(raw_preds > 0, 1, -1)
    return raw_preds

In [28]:
def accuracy(pred, labels):
    results = np.where(pred==labels, 1, 0)
    acc = results.sum()/len(results)*100
    return acc.item()

In [29]:
training_pred = predictions(
    trained_w=t_w,
    trained_b=t_b,
    X=X_train
)

In [30]:
# checking training set accuracy
train_acc = accuracy(
    pred=training_pred,
    labels=Y_train
)
print(f"Accuracy on training data: {train_acc:.2f} %")

Accuracy on training data: 94.51 %


In [31]:
# checking test set accuracy
test_pred = predictions(
    trained_w=t_w,
    trained_b=t_b,
    X=X_test
)

In [32]:
test_acc = accuracy(
    pred=test_pred,
    labels=Y_test
)
print(f"Accuracy on test data: {test_acc:.2f} %")

Accuracy on test data: 97.37 %


In [33]:
np.unique(test_pred)

array([-1,  1])

In [42]:
def confusion_matrix(predictions, labels):
    Tp = np.where((predictions == 1) & (labels == 1), 1, 0).sum()
    Fp = np.where((predictions == 1) & (labels == -1), 1, 0).sum()
    Fn = np.where((predictions == -1) & (labels == 1), 1, 0).sum()
    Tn = np.where((predictions == -1) & (labels == -1), 1, 0).sum()
    pre = Tp/(Tp + Fp)
    recall = Tp/(Tp + Fn)
    f1 = 2*(pre * recall)/(pre + recall)

    return {
        "True_Positive": Tp.item(),
        "False_Positive": Fp.item(),
        "False_Negative": Fn.item(), 
        "True_Negative": Tn.item(),
        "Precision": round(pre.item()*100, 2),
        "recall": round(recall.item()*100, 2),
        "F1": f1.item()
    }


In [43]:
confu_mat = confusion_matrix(predictions=training_pred, labels=Y_train)

In [44]:
confu_mat

{'True_Positive': 283,
 'False_Positive': 23,
 'False_Negative': 2,
 'True_Negative': 147,
 'Precision': 92.48,
 'recall': 99.3,
 'F1': 0.9576988155668359}

## Now that we have implemented SVM from scratch but now see the abstraction, and compare the performance

In [16]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [17]:
X = df[[col for col in df.columns if col not in ["id", "diagnosis"]]]
Y = df["diagnosis"]

In [18]:
scalar = StandardScaler()
X_scaled = scalar.fit_transform(X)

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)

In [20]:
soft_svm = SVC(kernel='linear', C=5.0)
soft_svm.fit(X=X_train, y=Y_train)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",5.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'linear'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide `.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide `.",False
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


### Training set

In [21]:
training_pred = soft_svm.predict(X_train)

In [22]:
accuracy_score(y_true=Y_train, y_pred=training_pred)

0.989010989010989

In [23]:
confusion_matrix(y_true=Y_train, y_pred=training_pred)

array([[165,   4],
       [  1, 285]])

In [24]:
f1_score(y_true=Y_train, y_pred=training_pred)

0.991304347826087

### Test Set

In [25]:
test_pred = soft_svm.predict(X=X_test)

In [26]:
accuracy_score(y_true=Y_test, y_pred=test_pred)

0.9649122807017544

In [27]:
confusion_matrix(y_true=Y_test, y_pred=test_pred)

array([[42,  1],
       [ 3, 68]])

In [28]:
f1_score(y_true=Y_test, y_pred=test_pred)

0.9714285714285714

In [30]:
from sklearn.svm import LinearSVC

In [56]:
primal_soft_svm1 = LinearSVC(
    dual=False,      
    C=5.0,           
    penalty='l2',    
    loss='squared_hinge', 
    max_iter=2000,
    class_weight='balanced'
)

In [59]:
primal_soft_svm1.fit(X=X_train, y=Y_train)

,"penalty penalty: {'l1', 'l2'}, default='l2'Specifies the norm used in the penalization. The 'l2'penalty is the standard used in SVC. The 'l1' leads to ``coef_``vectors that are sparse.",'l2'
,"loss loss: {'hinge', 'squared_hinge'}, default='squared_hinge'Specifies the loss function. 'hinge' is the standard SVM loss(used e.g. by the SVC class) while 'squared_hinge' is thesquare of the hinge loss. The combination of ``penalty='l1'``and ``loss='hinge'`` is not supported.",'squared_hinge'
,"dual dual: ""auto"" or bool, default=""auto""Select the algorithm to either solve the dual or primaloptimization problem. Prefer dual=False when n_samples > n_features.`dual=""auto""` will choose the value of the parameter automatically,based on the values of `n_samples`, `n_features`, `loss`, `multi_class`and `penalty`. If `n_samples` < `n_features` and optimizer supportschosen `loss`, `multi_class` and `penalty`, then dual will be set to True,otherwise it will be set to False... versionchanged:: 1.3 The `""auto""` option is added in version 1.3 and will be the default in version 1.5.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.For an intuitive visualization of the effects of scalingthe regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",5.0
,"multi_class multi_class: {'ovr', 'crammer_singer'}, default='ovr'Determines the multi-class strategy if `y` contains more thantwo classes.``""ovr""`` trains n_classes one-vs-rest classifiers, while``""crammer_singer""`` optimizes a joint objective over all classes.While `crammer_singer` is interesting from a theoretical perspectiveas it is consistent, it is seldom used in practice as it rarely leadsto better accuracy and is more expensive to compute.If ``""crammer_singer""`` is chosen, the options loss, penalty and dualwill be ignored.",'ovr'
,"fit_intercept fit_intercept: bool, default=TrueWhether or not to fit an intercept. If set to True, the feature vectoris extended to include an intercept term: `[x_1, ..., x_n, 1]`, where1 corresponds to the intercept. If set to False, no intercept will beused in calculations (i.e. data is expected to be already centered).",True
,"intercept_scaling intercept_scaling: float, default=1.0When `fit_intercept` is True, the instance vector x becomes ``[x_1,..., x_n, intercept_scaling]``, i.e. a ""synthetic"" feature with aconstant value equal to `intercept_scaling` is appended to the instancevector. The intercept becomes intercept_scaling * synthetic featureweight. Note that liblinear internally penalizes the intercept,treating it like any other term in the feature vector. To reduce theimpact of the regularization on the intercept, the `intercept_scaling`parameter can be set to a value greater than 1; the higher the value of`intercept_scaling`, the lower the impact of regularization on it.Then, the weights become `[w_x_1, ..., w_x_n,w_intercept*intercept_scaling]`, where `w_x_1, ..., w_x_n` representthe feature weights and the intercept weight is scaled by`intercept_scaling`. This scaling allows the intercept term to have adifferent regularization behavior compared to the other features.",1
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to ``class_weight[i]*C`` forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",'balanced'
,"verbose verbose: int, default=0Enable verbose output. Note that this setting takes advantage of aper-process runtime setting in liblinear that, if enabled, may not workproperly in a multithreaded context.",0
,"random_state random_state: int, RandomState instance or None, default=NoneControls the pseudo

In [60]:
train_predictions = primal_soft_svm1.predict(X=X_train)

In [61]:
accuracy_score(y_true=Y_train, y_pred=train_predictions)

0.9912087912087912

In [62]:
confusion_matrix(y_true=Y_train, y_pred=train_predictions)

array([[167,   2],
       [  2, 284]])

In [63]:
f1_score(y_true=Y_train, y_pred=train_predictions)

0.993006993006993

In [64]:
primal_soft_svm2 = LinearSVC(
    dual=False,      
    C=5.0,           
    penalty='l2',    
    loss='squared_hinge',
    max_iter=2000,
)

In [65]:
primal_soft_svm2.fit(X=X_train, y=Y_train)

,"penalty penalty: {'l1', 'l2'}, default='l2'Specifies the norm used in the penalization. The 'l2'penalty is the standard used in SVC. The 'l1' leads to ``coef_``vectors that are sparse.",'l2'
,"loss loss: {'hinge', 'squared_hinge'}, default='squared_hinge'Specifies the loss function. 'hinge' is the standard SVM loss(used e.g. by the SVC class) while 'squared_hinge' is thesquare of the hinge loss. The combination of ``penalty='l1'``and ``loss='hinge'`` is not supported.",'squared_hinge'
,"dual dual: ""auto"" or bool, default=""auto""Select the algorithm to either solve the dual or primaloptimization problem. Prefer dual=False when n_samples > n_features.`dual=""auto""` will choose the value of the parameter automatically,based on the values of `n_samples`, `n_features`, `loss`, `multi_class`and `penalty`. If `n_samples` < `n_features` and optimizer supportschosen `loss`, `multi_class` and `penalty`, then dual will be set to True,otherwise it will be set to False... versionchanged:: 1.3 The `""auto""` option is added in version 1.3 and will be the default in version 1.5.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.For an intuitive visualization of the effects of scalingthe regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",5.0
,"multi_class multi_class: {'ovr', 'crammer_singer'}, default='ovr'Determines the multi-class strategy if `y` contains more thantwo classes.``""ovr""`` trains n_classes one-vs-rest classifiers, while``""crammer_singer""`` optimizes a joint objective over all classes.While `crammer_singer` is interesting from a theoretical perspectiveas it is consistent, it is seldom used in practice as it rarely leadsto better accuracy and is more expensive to compute.If ``""crammer_singer""`` is chosen, the options loss, penalty and dualwill be ignored.",'ovr'
,"fit_intercept fit_intercept: bool, default=TrueWhether or not to fit an intercept. If set to True, the feature vectoris extended to include an intercept term: `[x_1, ..., x_n, 1]`, where1 corresponds to the intercept. If set to False, no intercept will beused in calculations (i.e. data is expected to be already centered).",True
,"intercept_scaling intercept_scaling: float, default=1.0When `fit_intercept` is True, the instance vector x becomes ``[x_1,..., x_n, intercept_scaling]``, i.e. a ""synthetic"" feature with aconstant value equal to `intercept_scaling` is appended to the instancevector. The intercept becomes intercept_scaling * synthetic featureweight. Note that liblinear internally penalizes the intercept,treating it like any other term in the feature vector. To reduce theimpact of the regularization on the intercept, the `intercept_scaling`parameter can be set to a value greater than 1; the higher the value of`intercept_scaling`, the lower the impact of regularization on it.Then, the weights become `[w_x_1, ..., w_x_n,w_intercept*intercept_scaling]`, where `w_x_1, ..., w_x_n` representthe feature weights and the intercept weight is scaled by`intercept_scaling`. This scaling allows the intercept term to have adifferent regularization behavior compared to the other features.",1
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to ``class_weight[i]*C`` forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: int, default=0Enable verbose output. Note that this setting takes advantage of aper-process runtime setting in liblinear that, if enabled, may not workproperly in a multithreaded context.",0
,"random_state random_state: int, RandomState instance or None, default=NoneControls the pseudo rando

In [66]:
train_predictions = primal_soft_svm2.predict(X=X_train)

In [67]:
accuracy_score(y_true=Y_train, y_pred=train_predictions)

0.9934065934065934

In [68]:
confusion_matrix(y_true=Y_train, y_pred=train_predictions)

array([[167,   2],
       [  1, 285]])

In [69]:
f1_score(y_true=Y_train, y_pred=train_predictions)

0.9947643979057592

In [70]:
test_predictions = primal_soft_svm2.predict(X=X_test)

In [71]:
accuracy_score(y_true=Y_test, y_pred=test_predictions)

0.956140350877193

In [72]:
confusion_matrix(y_true=Y_test, y_pred=test_predictions)

array([[42,  1],
       [ 4, 67]])

In [73]:
f1_score(y_true=Y_test, y_pred=test_predictions)

0.9640287769784173

In [74]:
test_predictions2 = primal_soft_svm1.predict(X=X_test)

In [75]:
accuracy_score(y_true=Y_test, y_pred=test_predictions2)

0.9385964912280702

In [76]:
confusion_matrix(y_true=Y_test, y_pred=test_predictions2)

array([[42,  1],
       [ 6, 65]])

In [78]:
f1_score(y_true=Y_test, y_pred=test_predictions2)

0.948905109489051