In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Literal

## Loading the data

In [2]:
cwd = Path.cwd()
project_root = cwd.parent
data_path = project_root / "data" / "improved_fraud_dataset.csv"

In [3]:
data = pd.read_csv(
    filepath_or_buffer=str(data_path),
    encoding='latin-1',
    sep=",",
    thousands=',',
    na_values=['NA', 'N/A', 'null', 'NULL', '', ' ', 'None'],
)

In [4]:
data.shape

(1000000, 24)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 24 columns):
 #   Column                 Non-Null Count    Dtype  
---  ------                 --------------    -----  
 0   organization           1000000 non-null  object 
 1   transaction_id         1000000 non-null  object 
 2   user_id                1000000 non-null  object 
 3   user_account_age_days  1000000 non-null  int64  
 4   kyc_verified           1000000 non-null  int64  
 5   payment_method         1000000 non-null  object 
 6   card_type              1000000 non-null  object 
 7   transaction_amount     1000000 non-null  float64
 8   currency               1000000 non-null  object 
 9   fee_amount             1000000 non-null  float64
 10  transaction_timestamp  1000000 non-null  object 
 11  day_of_week            1000000 non-null  object 
 12  city                   1000000 non-null  object 
 13  country                1000000 non-null  object 
 14  device_type        

In [6]:
data.notna().all().all()

np.True_

In [7]:
data.columns

Index(['organization', 'transaction_id', 'user_id', 'user_account_age_days',
       'kyc_verified', 'payment_method', 'card_type', 'transaction_amount',
       'currency', 'fee_amount', 'transaction_timestamp', 'day_of_week',
       'city', 'country', 'device_type', 'operating_system', 'browser',
       'merchant_category', 'transaction_type', 'otp_used', 'is_fraud', 'hour',
       'is_night', 'time_diff'],
      dtype='object')

In [8]:
object_cols = [col for col in data.columns if data[col].dtype == 'object']

In [9]:
object_cols

['organization',
 'transaction_id',
 'user_id',
 'payment_method',
 'card_type',
 'currency',
 'transaction_timestamp',
 'day_of_week',
 'city',
 'country',
 'device_type',
 'operating_system',
 'browser',
 'merchant_category',
 'transaction_type']

In [10]:
obj_unique_vals = {key:list(data[key].unique()) for key in object_cols}

In [11]:
obj_unique_vals

{'organization': ['FinovaTech_000',
  'FinovaTech_001',
  'FinovaTech_002',
  'FinovaTech_003',
  'FinovaTech_004',
  'FinovaTech_005',
  'FinovaTech_006',
  'FinovaTech_007',
  'FinovaTech_008',
  'FinovaTech_009',
  'FinovaTech_010',
  'FinovaTech_011',
  'FinovaTech_012',
  'FinovaTech_013',
  'FinovaTech_014',
  'FinovaTech_015',
  'FinovaTech_016',
  'FinovaTech_017',
  'FinovaTech_018',
  'FinovaTech_019',
  'FinovaTech_020',
  'FinovaTech_021',
  'FinovaTech_022',
  'FinovaTech_023',
  'FinovaTech_024',
  'FinovaTech_025',
  'FinovaTech_026',
  'FinovaTech_027',
  'FinovaTech_028',
  'FinovaTech_029',
  'FinovaTech_030',
  'FinovaTech_031',
  'FinovaTech_032',
  'FinovaTech_033',
  'FinovaTech_034',
  'FinovaTech_035',
  'FinovaTech_036',
  'FinovaTech_037',
  'FinovaTech_038',
  'FinovaTech_039',
  'FinovaTech_040',
  'FinovaTech_041',
  'FinovaTech_042',
  'FinovaTech_043',
  'FinovaTech_044',
  'FinovaTech_045',
  'FinovaTech_046',
  'FinovaTech_047',
  'FinovaTech_048',
  'F

## Ok, First Let's just build the network from scratch

In [72]:
# defining some hyperparameters
BATCH_SIZE = 256
config = [2, 2, 4, 1]
ACTIVATION : Literal['sigmoid', 'relu'] = 'sigmoid'
OUT_ACTICATION = 'sigmoid'

In [73]:
def initialize_hidden_parameters(
        config: list[int],
):
    weights = []
    baises = []
    for i in range(len(config)-1):
        w = np.random.randint(size=(config[i], config[i+1]), low=0, high=10)
        b = np.random.randint(size=(1, config[i+1]), low=0, high=10)

        weights.append(w)
        baises.append(b)

    return weights, baises

In [74]:
weights, baises = initialize_hidden_parameters(config=config)

In [75]:
len(weights), len(baises)

(3, 3)

In [76]:
weights[0].shape, baises[0].shape

((2, 2), (1, 2))

In [77]:
def sigmoid(Z:np.array):
    return 1/(1+np.exp(-Z))

In [78]:
def forward_propagation(
        X: np.array,
		weights: np.array,
        baises: np.array,
):
    activations = X
    print(f"Data: {X}\n")
    for i in range(len(weights)):
        Z = activations @ weights[i] + baises[i]
        print(f"Layer {i+1}: Z: {Z}\n")
        activations = sigmoid(Z)
        print(f"Layer {i+1}: activations: {activations}\n")
        
    return activations

In [79]:
weights, baises = initialize_hidden_parameters(config=config)

In [86]:
X = np.random.randint(size=(3, 2), low=0, high=5)

In [87]:
output = forward_propagation(
    X=X,
    weights=weights,
    baises=baises
)

Data: [[2 3]
 [0 2]
 [4 4]]

Layer 1: Z: [[37 34]
 [16 16]
 [58 52]]

Layer 1: activations: [[1.         1.        ]
 [0.99999989 0.99999989]
 [1.         1.        ]]

Layer 2: Z: [[11.         14.         12.         20.        ]
 [10.99999932 13.99999854 11.99999876 19.99999831]
 [11.         14.         12.         20.        ]]

Layer 2: activations: [[0.9999833  0.99999917 0.99999386 1.        ]
 [0.9999833  0.99999917 0.99999386 1.        ]
 [0.9999833  0.99999917 0.99999386 1.        ]]

Layer 3: Z: [[25.99989492]
 [25.99989492]
 [25.99989492]]

Layer 3: activations: [[1.]
 [1.]
 [1.]]



In [89]:
weights[0],baises[0]

(array([[8, 5],
        [5, 8]]),
 array([[6, 0]]))

In [91]:
weights[1], baises[1]

(array([[0, 4, 9, 6],
        [6, 9, 2, 9]]),
 array([[5, 1, 1, 5]]))